---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[master::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      docker_version: '18.09.4'
      user:
        name: kuser
        pw_hash: '$6$v5d7PRMZZxjuMCTw$YpJQaGQQoiThV61w2byWYwgZnXFQa5Ns6I/VEhPvqejiGgsesgLXOddaZerSMIUaGXj5gqLWgGqh0AIZOkGoU0'
        ssh_public_key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMQF8kIrvIgklKRUDT8naQHog1O+4sCZaK35bq2SI4WlyFPWaVTDeXXXST9blsptRn8IuZ0krMSXeONJJsbT4Ww= test@testhost'
